# Generated by Django 4.2 on 2024-12-19 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('seller_id', models.AutoField(primary_key=True, serialize=False)),
                ('names', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=128)),
                ('district', models.CharField(max_length=32)),
                ('sector', models.CharField(max_length=32)),
                ('telephone', models.CharField(max_length=13)),
                ('username', models.CharField(max_length=32, unique=True)),
            ],
        ),
    ]
