# Generated by Django 5.1.4 on 2024-12-18 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sellers',
            fields=[
                ('seller_id', models.IntegerField(primary_key=True, serialize=False)),
                ('names', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=32)),
                ('district', models.CharField(max_length=32)),
                ('sector', models.CharField(max_length=32)),
                ('telephone', models.CharField(max_length=13)),
                ('username', models.CharField(max_length=32)),
            ],
        ),
    ]
