# Generated by Django 4.2 on 2024-12-23 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sellers', '0004_seller_profile_picture_alter_seller_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='seller_id',
            new_name='id',
        ),
    ]
