# Generated by Django 4.2 on 2024-12-19 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Sellers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('stock_quantity', models.IntegerField()),
                ('unit', models.CharField(max_length=3)),
                ('minimum_for_deliver', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sellers.seller')),
            ],
        ),
    ]
